version: '3.1'
services:
  # app:
  #   depends_on:
  #     - db
  #   build: .
  #   volumes:
  #     - '.:/app/'
  #   environment:
  #     POSTGRES_HOST: db
  #   ports:
  #     - 8000:8000
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_HOST_PORT}:5432

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
